apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokoete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokoete
  template:
    metadata:
      labels:
        app: tokoete
    spec:
      containers:
      - image: okteto.dev/tokoete:latest
        name: tokoete
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "720d5f36-d896-43cc-a866-751f9352180e"
        - name: Vless_Path
          value: "/vl5fshe"
        - name: Vmess_UUID
          value: "720d5f36-d896-43cc-a866-751f9352180e"
        - name: Vmess_Path
          value: "/vm6huik"
        - name: Share_Path
          value: "/v2link"
